[project]
name = "langgraph-mcp-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "huggingface-hub==0.31.4",
    "langgraph==0.4.5",
    "python-dotenv==1.1.0",
]
